server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route #路由的id，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由
        - id: payment_routh2  #payment_route #路由的id，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的路由地址
          #gatewayFilter：https://docs.spring.io/spring-cloud-gateway/docs/2.2.9.RELEASE/reference/html/#gatewayfilter-factories
          #globalFilter：https://docs.spring.io/spring-cloud-gateway/docs/2.2.9.RELEASE/reference/html/#global-filters
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/lb  #断言，路径相匹配的进行路由
#            - After=2022-12-16T15:29:47.129+08:00[Asia/Shanghai]   #该时间点之后的才能访问
#            - Before=2022-12-16T15:29:47.129+08:00[Asia/Shanghai]  #该时间点之前的才能访问
#            - Between=2022-12-16T15:29:47.129+08:00[Asia/Shanghai],2022-12-16T15:29:47.129+08:00[Asia/Shanghai] #该时间段内才能访问
#            - Cookie=username,zzyy #cookie满足条件的才能访问   #cmd测试：curl http://localhost:9527/payment/lb --cookie "username=zzyy"
#            - Header=X-Request-Id,\d+  #请求头要有X-Request-Id属性，并且值为整数（正数）的正则表达式  #cmd测试：curl http://localhost:9527/payment/lb -H "X-Request-Id:1a"
#            - Host=**.atguigu.com
#            - Method=GET,POST
#            - Query=username,\d+  #要有参数名username，并且值为正正数才能访问

eureka:
  instance:
    hostname: cloud-gateway-service
    prefer-ip-address: true
    instance-id: cloud-gateway9527
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/


