server:
  port: 8004
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      discovery:
          connect-string: 127.0.0.1:2181
#com:
#  kd:
#    config:
#      enabled: true
